# Generated by Django 3.0.6 on 2020-07-14 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0004_auto_20200714_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 14, 12, 56, 42, 709931, tzinfo=utc)),
        ),
    ]
